export const keys = {
  Backquote: { sign: "`", shift: "~", code: 192 },
  Digit1: { sign: "1", shift: "!", code: 49 },
  Digit2: { sign: "2", shift: "@", code: 50 },
  Digit3: { sign: "3", shift: "#", code: 51 },
  Digit4: { sign: "4", shift: "$", code: 52 },
  Digit5: { sign: "5", shift: "%", code: 53 },
  Digit6: { sign: "6", shift: "^", code: 54 },
  Digit7: { sign: "7", shift: "&", code: 55 },
  Digit8: { sign: "8", shift: "*", code: 56 },
  Digit9: { sign: "9", shift: "(", code: 57 },
  Digit0: { sign: "0", shift: ")", code: 48 },
  Minus: { sign: "-", shift: "_", code: 189 },
  Equal: { sign: "=", shift: "+", code: 187 },
  Backspace: { sign: "Backspace", shift: null, code: 8 },
  Tab: { sign: "Tab", shift: null, code: 9 },
  KeyQ: { sign: "q", shift: "Q", code: 81 },
  KeyW: { sign: "w", shift: "W", code: 87 },
  KeyE: { sign: "e", shift: "E", code: 69 },
  KeyR: { sign: "r", shift: "R", code: 82 },
  KeyT: { sign: "t", shift: "T", code: 84 },
  KeyY: { sign: "y", shift: "Y", code: 89 },
  KeyU: { sign: "u", shift: "U", code: 85 },
  KeyI: { sign: "i", shift: "I", code: 73 },
  KeyO: { sign: "o", shift: "O", code: 79 },
  KeyP: { sign: "p", shift: "P", code: 80 },
  BracketLeft: { sign: "[", shift: "{", code: 219 },
  BracketRight: { sign: "]", shift: "}", code: 221 },
  Delete: { sign: "DEL", shift: null, code: 46 },
  CapsLock: { sign: "Caps Lock", shift: null, code: 20 },
  KeyA: { sign: "a", shift: "A", code: 65 },
  KeyS: { sign: "s", shift: "S", code: 83 },
  KeyD: { sign: "d", shift: "D", code: 68 },
  KeyF: { sign: "f", shift: "F", code: 70 },
  KeyG: { sign: "g", shift: "G", code: 71 },
  KeyH: { sign: "h", shift: "H", code: 72 },
  KeyJ: { sign: "j", shift: "J", code: 74 },
  KeyK: { sign: "k", shift: "K", code: 75 },
  KeyL: { sign: "l", shift: "L", code: 76 },
  Semicolon: { sign: ";", shift: ":", code: 186 },
  Quote: { sign: "'", shift: '"', code: 222 },
  Backslash: { sign: "\\", shift: "|", code: 220 },
  Enter: { sign: "ENTER", shift: null, code: 13 },
  ShiftLeft: {
    sign: "Shift",
    position: "ShiftLeft",
    shift: null,
    code: 16,
  },
  KeyZ: { sign: "z", shift: "Z", code: 90 },
  KeyX: { sign: "x", shift: "X", code: 88 },
  KeyC: { sign: "c", shift: "C", code: 67 },
  KeyV: { sign: "v", shift: "V", code: 86 },
  KeyB: { sign: "b", shift: "B", code: 66 },
  KeyN: { sign: "n", shift: "N", code: 78 },
  KeyM: { sign: "m", shift: "M", code: 77 },
  Comma: { sign: ",", shift: "<", code: 188 },
  Period: { sign: ".", shift: ">", code: 190 },
  Slash: { sign: "/", shift: "?", code: 191 },
  ArrowUp: { sign: "ᐃ", key: "ArrowUp", shift: null, code: 38 },
  ShiftRight: { sign: "Shift", position: "ShiftRight", shift: null, code: 16 },
  ControlLeft: { sign: "Ctrl", position: "ControlLeft", shift: null, code: 17 },
  AltLeft: { sign: "Alt", position: "AltLeft", shift: null, code: 18 },
  Space: { sign: " ", shift: null, code: 32 },
  AltRight: { sign: "Alt", position: "AltRight", shift: null, code: 18 },
  ControlRight: {
    sign: "Ctrl",
    position: "ControlRight",
    shift: null,
    code: 17,
  },
  ArrowLeft: { sign: "ᐊ", key: "ArrowLeft", shift: null, code: 37 },
  ArrowDown: { sign: "ᐁ", key: "ArrowDown", shift: null, code: 40 },
  ArrowRight: { sign: "ᐅ", key: "ArrowRight", shift: null, code: 39 },
};
