export const keys = {
  Backquote: { sign: "`", shift: "~", code: "Backquote" },
  Digit1: { sign: "1", shift: "!", code: "Digit1" },
  Digit2: { sign: "2", shift: "@", code: "Digit2" },
  Digit3: { sign: "3", shift: "#", code: "Digit3" },
  Digit4: { sign: "4", shift: "$", code: "Digit4" },
  Digit5: { sign: "5", shift: "%", code: "Digit5" },
  Digit6: { sign: "6", shift: "^", code: "Digit6" },
  Digit7: { sign: "7", shift: "&", code: "Digit7" },
  Digit8: { sign: "8", shift: "*", code: "Digit8" },
  Digit9: { sign: "9", shift: "(", code: "Digit9" },
  Digit0: { sign: "0", shift: ")", code: "Digit0" },
  Minus: { sign: "-", shift: "_", code: "Minus" },
  Equal: { sign: "=", shift: "+", code: "Equal" },
  Backspace: { sign: "Backspace", shift: null, code: "Backspace" },
  Tab: { sign: "Tab", shift: null, code: "Tab" },
  KeyQ: { sign: "q", shift: "Q", code: "KeyQ" },
  KeyW: { sign: "w", shift: "W", code: "KeyW" },
  KeyE: { sign: "e", shift: "E", code: "KeyE" },
  KeyR: { sign: "r", shift: "R", code: "KeyR" },
  KeyT: { sign: "t", shift: "T", code: "KeyT" },
  KeyY: { sign: "y", shift: "Y", code: "KeyY" },
  KeyU: { sign: "u", shift: "U", code: "KeyU" },
  KeyI: { sign: "i", shift: "I", code: "KeyI" },
  KeyO: { sign: "o", shift: "O", code: "KeyO" },
  KeyP: { sign: "p", shift: "P", code: "KeyP" },
  BracketLeft: { sign: "[", shift: "{", code: "BracketLeft" },
  BracketRight: { sign: "]", shift: "}", code: "BracketRight" },
  Delete: { sign: "DEL", shift: null, code: "Delete" },
  CapsLock: { sign: "Caps Lock", shift: null, code: "CapsLock" },
  KeyA: { sign: "a", shift: "A", code: "KeyA" },
  KeyS: { sign: "s", shift: "S", code: "KeyS" },
  KeyD: { sign: "d", shift: "D", code: "KeyD" },
  KeyF: { sign: "f", shift: "F", code: "KeyF" },
  KeyG: { sign: "g", shift: "G", code: "KeyG" },
  KeyH: { sign: "h", shift: "H", code: "KeyH" },
  KeyJ: { sign: "j", shift: "J", code: "KeyJ" },
  KeyK: { sign: "k", shift: "K", code: "KeyK" },
  KeyL: { sign: "l", shift: "L", code: "KeyL" },
  Semicolon: { sign: ";", shift: ":", code: "Semicolon" },
  Quote: { sign: "'", shift: '"', code: "Quote" },
  Backslash: { sign: "\\", shift: "|", code: "Backslash" },
  Enter: { sign: "ENTER", shift: null, code: "Enter" },
  ShiftLeft: {
    sign: "Shift",
    position: "ShiftLeft",
    shift: null,
    code: "Shift",
  },
  KeyZ: { sign: "z", shift: "Z", code: "KeyZ" },
  KeyX: { sign: "x", shift: "X", code: "KeyX" },
  KeyC: { sign: "c", shift: "C", code: "KeyC" },
  KeyV: { sign: "v", shift: "V", code: "KeyV" },
  KeyB: { sign: "b", shift: "B", code: "KeyB" },
  KeyN: { sign: "n", shift: "N", code: "KeyN" },
  KeyM: { sign: "m", shift: "M", code: "KeyM" },
  Comma: { sign: ",", shift: "<", code: "Comma" },
  Period: { sign: ".", shift: ">", code: "Period" },
  Slash: { sign: "/", shift: "?", code: "Slash" },
  ArrowUp: { sign: "ᐃ", key: "ArrowUp", shift: null, code: "ArrowUp" },
  ShiftRight: {
    sign: "Shift",
    position: "ShiftRight",
    shift: null,
    code: "Shift",
  },
  ControlLeft: {
    sign: "Ctrl",
    position: "ControlLeft",
    shift: null,
    code: "Control",
  },
  AltLeft: { sign: "Alt", position: "AltLeft", shift: null, code: "Alt" },
  Space: { sign: " ", shift: null, code: "Space" },
  AltRight: { sign: "Alt", position: "AltRight", shift: null, code: "Alt" },
  ControlRight: {
    sign: "Ctrl",
    position: "ControlRight",
    shift: null,
    code: "Control",
  },
  ArrowLeft: { sign: "ᐊ", key: "ArrowLeft", shift: null, code: "ArrowLeft" },
  ArrowDown: { sign: "ᐁ", key: "ArrowDown", shift: null, code: "ArrowDown" },
  ArrowRight: { sign: "ᐅ", key: "ArrowRight", shift: null, code: "ArrowRight" },
};
